name: SnapQueue CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Runs Format Check
        run: npm run format:check

      - name: Build Check
        run: npm run build

      - name: Build Docker Image
        run: docker build -t snapqueue-app .

      - name: Run Container
        run: docker  run -d -p 3000:3000 --name snapqueue-container snapqueue-app

      - name: Cleanup
        if: always()
        run: |
          docker stop snapqueue-container || true
          docker rm snapqueue-container || true